export const projects = [
  {
    id: "web-pro-1",
    image: "image/project-image/banner-akomate.jpg",
    title: "Akomate Software Hotel",
    desc: "Hotel Landing Page Website",
    job: "Redevelop Website with New Design and Implementing SEO Engine (Google and Hotjar) also Google Recaptcha to the Website",
    url: "https://akomatehotelsoftware.com",
    tech: ["HTML", "CSS", "JS", "PHP"],
  },
  {
    id: "web-pro-2",
    image: "image/project-image/banner-ontegode.jpg",
    title: "Ontego Business Mobility",
    desc: "Software Solutions for Mobile Age",
    job: "Make Product on Page Mobile Geraete More Dynamic by Fetching Data from API Skybase",
    url: "https://ontego.de/",
    tech: ["HTML", "CSS", "JS", "PHP"],
  },
  {
    id: "web-pro-3",
    image: "image/project-image/banner-wscommsult.jpg",
    title: "Welcome Screen commsult",
    desc: "Welcome Screen commsult Website",
    job: "Develop Animation Logo commsult and Slider",
    url: "https://ws.commsult.de/",
    tech: ["HTML", "CSS", "JS", "PHP"],
  },
  {
    id: "web-pro-4",
    image: "image/project-image/banner-commsult.jpg",
    title: "commsult Website",
    desc: "commsult Profile Website",
    job: "Redevelop commsult Website with New Design and Implement Animation on Some Page",
    url: "https://commsult.de/",
    tech: ["HTML", "CSS", "JS"],
  },
];
